language: python
python:
  - "3.5"
  - "3.5"
  - "3.6"
  - "nightly"
# command to run tests
script:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.4 || $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test;else pytest; fi